using System.Text.Json.Serialization;

namespace Bosqora.Heyzine.Models;

/// <summary>
/// Represents the response returned by the sync and async conversion endpoints.
/// </summary>
public class HeyzineResponse
{
    /// <summary>
    /// Gets or sets the generated flipbook identifier.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Gets or sets the conversion metadata, including page count and aspect ratio.
    /// </summary>
    [JsonPropertyName("meta")]
    public HeyzineMetadata Metadata { get; set; } = new();

    /// <summary>
    /// Gets or sets the hosted PDF URL generated by Heyzine.
    /// </summary>
    public Uri? Pdf { get; set; }

    /// <summary>
    /// Gets or sets the async conversion state, such as "started", "processed", or "failed".
    /// </summary>
    public string? State { get; set; }

    /// <summary>
    /// Gets or sets the generated thumbnail URL.
    /// </summary>
    public Uri? Thumbnail { get; set; }

    /// <summary>
    /// Gets or sets the public URL of the generated flipbook.
    /// </summary>
    public Uri? Url { get; set; }
}