using System.Text.Json.Serialization;

namespace Bosqora.Heyzine.Models;

/// <summary>
/// Represents the public links returned for a flipbook.
/// </summary>
public class HeyzineFlipbookLinks
{
    /// <summary>
    /// Gets or sets the default Heyzine URL for the flipbook.
    /// </summary>
    [JsonPropertyName("base")]
    public Uri? Base { get; set; }

    /// <summary>
    /// Gets or sets the custom-domain URL for the flipbook when one is configured.
    /// </summary>
    public Uri? Custom { get; set; }

    /// <summary>
    /// Gets or sets the hosted PDF URL generated by Heyzine.
    /// </summary>
    public Uri? Pdf { get; set; }

    /// <summary>
    /// Gets or sets the flipbook cover thumbnail URL.
    /// </summary>
    public Uri? Thumbnail { get; set; }
}